language: csharp 
dist: trusty
os: linux
dotnet: 2.1.2
mono: none
install:
- dotnet restore ./BlogManagement/Blogging.sln
script:
 - dotnet --info
 - dotnet build ./BlogManagement/Blogging.sln
 - ls -a